### ISSUE TITLE
When Natural Increase is false noteblock sound still plays

### ISSUE THREAD

**Issue by ajh123** [Team-Inceptus/Novaconomy#121]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.20.1 (any MC version that can run Novaconomy 1.8.2)

### Description

When natural increase is disabled the noteblock sound still gets played every time a natural increase is supposed to happen.

### Steps to Reproduce

1. Create an economy
2. Disable natural increase like `/econ naturalincrease <economy name>false`
3. Do some things that trigger natural increase (like building or destroying)
4. Hear that note block sound that happens when natural increase occurs if it's enabled 

### Expected Behavior

Just like the action bar message when the economy's natural increase is disabled the note block should be to.

### Actual Behavior

The note block sound is played when doing natural increase causes (like building or destroying) when natural increase is disabled for the economy.

### Additional Info

Command 2 in #117 still fails in this version. Also, this issue was present in the snapshots for 1.8.2.

**Comment by GamerCoder215** [comment]
Fixed and tested in 23c2ef6.
