### ISSUE TITLE
overwrite /help

### ISSUE THREAD

**Issue by mineblow** [Team-Inceptus/Novaconomy#127]
### Bug Type

Compatibility Issues, Other Unexpected Behavior

### Minecraft Version

1.20

### Description

using advanced help plugin along side nova economy. nova economy seems to be overriding /help command. with advanced help /help should be able to open a gui, its not it just lists nova economy commands. remove nova economy /help works as expected/

### Steps to Reproduce

run advanced help and nova economy along side each other do /help

### Expected Behavior

should open a gui when doing /help does not.

### Actual Behavior

there are no errors shown in console

**Comment by GamerCoder215** [comment]
I'll have to test this. For now, append the plugin's name with a colon to fix. So it would be `/advancedhelp:help` or something.

**Comment by GamerCoder215** [comment]
> ### Bug Type
> 
> Compatibility Issues, Other Unexpected Behavior
> ### Minecraft Version
> 
> 1.20
> ### Description
> 
> using advanced help plugin along side nova economy. nova economy seems to be overriding /help command. with advanced help /help should be able to open a gui, its not it just lists nova economy commands. remove nova economy /help works as expected/
> ### Steps to Reproduce
> 
> run advanced help and nova economy along side each other do /help
> ### Expected Behavior
> 
> should open a gui when doing /help does not.
> ### Actual Behavior
> 
> there are no errors shown in console
> ### Additional Info
> 
> _No response_

Novaconomy has no impact on Advanced Help, as Novaconomy does not override any commands. 1.13.2+ and above uses a command framework that registers our commands at runtime, but this should still not have any impact on a separate plugin. Contact the plugin developer with your issue.
