### ISSUE TITLE
1.20.5 Support

### ISSUE THREAD

**Issue by gmitch215** [Team-Inceptus/Novaconomy#146]
### Feature Type

Compatibility

### Description of Feature

Notes for 1.20.5 support added here.

**Comment by Link0Darck** [comment]
and 1.20.6 please

**Comment by gmitch215** [comment]
> and 1.20.6 please

1.20.6 is essentially the same as 1.20.5, if you need immediate support right now you can read [this page](https://github.com/Team-Inceptus/Novaconomy/wiki/Using-Experiemental-Versions) with `ver/1.10.0`
