### ISSUE TITLE
SignShop support?

### ISSUE THREAD

**Issue by vertexofvortex** [Team-Inceptus/Novaconomy#148]
### Bug Type

Compatibility Issues

### Minecraft Version

1.20.4 (Novaconomy 1.9.2)

### Description

I was trying to create a sign-driven shop with [this classic plugin](https://www.spigotmc.org/resources/signshop.10997/). Its Spigot page says that plugin is compatible with any Vault-based economy plugin, but here's the problem.

### Steps to Reproduce

It turns out that SignShop, although it is possible to work with a default (the first one if there are many of them or the only one available) currency in Novaconomy, it cannot see the player's balance.

Here's my currency and the player's balance:

![image](https://github.com/Team-Inceptus/Novaconomy/assets/31506708/29e78ded-5ea8-4289-8815-e405a67673a2)

And here I'm trying to buy something via shop sign:

![2024-04-28_15 46 32](https://github.com/Team-Inceptus/Novaconomy/assets/31506708/eaff86a0-4f30-4a1d-aa60-82b9b64bb4e9)

Vault also can see multiple currencies:

```[15:52:23] [Render thread/INFO]: [System] [CHAT] [Vault] Vault v1.7.3-b131 Information
[15:52:23] [Render thread/INFO]: [System] [CHAT] [Vault] Economy: Diamonds [Diamonds, Netherite]
[15:52:23] [Render thread/INFO]: [System] [CHAT] [Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
[15:52:23] [Render thread/INFO]: [System] [CHAT] [Vault] Chat: LuckPerms [LuckPerms]
````

### Expected Behavior

I expect Novaconomy wallet to work with SignShop plugin.

### Actual Behavior

It refuses to work =(

### Additional Info

I think that issue is more related to your plugin rather than Vault or SignShop. If there is a workaround available, please let me know. If there is no way to make multicurrency plugin working with SignShop, it would be great if in-world trading features like shop signs were implemented in Novaconomy.

**Comment by gmitch215** [comment]
Because Vault (and therefore plugins that use it) only supports *one* economy, you need to set an economy that it uses. Your config shows that all the economies are registered, and that it's using the first one (`Diamonds`), but there is probably some weird functionality regarding there being multiple.

To change this, look at `VaultEconomy` in `functionality.yml` (also read [this wiki page](https://github.com/Team-Inceptus/Novaconomy/wiki/Integrations-%7C-Vault)).

Let me know if this doesn't work.

**Comment by vertexofvortex** [comment]
Tried to set `VaultEconomy: Diamonds` in the config. It does no effect. Even if it is a single available economy.

**Comment by gmitch215** [comment]
> Tried to set `VaultEconomy: Diamonds` in the config. It does no effect. Even if it is a single available economy.

Will to attempt to reproduce the bug.

While I do this, can you confirm that SignShop correctly works with Vault? Perhaps by trying with a different economy provider (e.g. Essentials)?

**Comment by vertexofvortex** [comment]
I will check this as soon as possible, post the results here.

**Comment by gmitch215** [comment]
Was doing too much research, and it ended up being one line of code :P.

See [this wiki page](https://github.com/Team-Inceptus/Novaconomy/wiki/Using-Experiemental-Versions) about using the experimental version.

**Comment by gmitch215** [comment]
> Just found a funny issue with the [ChestShop plugin](https://www.spigotmc.org/resources/chestshop.51856/): if you're buying something from a chest shop, you will buy it for ALL the money you have on the balance, regardless of the specified price. But if you try to sell, you will sell that item for a specified on the sign price only.

This is most likely due to what I mentioned earlier, since Vault is designed for one currency.
