### ISSUE TITLE
Exchange GUI v.3

### ISSUE THREAD

**Issue by SimpleWayx** [Team-Inceptus/Novaconomy#31]
### Feature Type

Optimization

### Description of Feature

Little improvement. When doing the /exchange there are some arguments that require to be done but they are not congruent to the final result.

In example.

doing the command /exchange 1000 money
When doing this command it shows the next following currency as 1000 Half-Moons (Next currency) and required money that is 10000 Money.

Showing me 1000 Half-Moons -> 10000 Money.
It should show 1000 Money -> 100 Half-Moons.
It looks weird. We place the maximum we desire to exchange for the minimum we can get.

I could recommend that in the exchange GUI. When someone just does /exchanges.
Have 4- 8 buttons the default economy. That starts at 100. And you can add 100-1k-10k to add or remove what is the minimum economy you desire to the maximum you can get.

Probably sounds difficult but could help to untrained users for easy access. 

 @ Also I am not so sure about how to put the default economy I desire into the vault (I know I can type them but not sure if it works or not) I want Money to be the default. 
 
 I am not completely sure about the implications of registering one economy as default rather than registering them all.
 
The problem of default economies keeps going on. I have the belief that is due that all economies are all registered and the one that has alphabetic priority gets to default.  Not sure what the implications of registering all economies are.
 
But let command facilitate the registration of such default economy my typing the name. If there is implications such as there is no database for the others.
 
 Show it here. and let do an extra command as /novaecon setdefaultecon confirm
 I am pretty sure most users would like to be money be by default the most used economy and the other economies as high priority yet individual economies.
 
 If you got questions about how we can think of a way and you could educate me about the implications. I'll be happy to help regarding critical thinking between users.

**Comment by GamerCoder215** [comment]
> ### Feature Type
> Optimization
> 
> ### Description of Feature
> Little improvement. When doing the /exchange there are some arguments that require to be done but they are not congruent to the final result.
> 
> In example.
> 
> doing the command /exchange 1000 money When doing this command it shows the next following currency as 1000 Half-Moons (Next currency) and required money that is 10000 Money.
> 
> Showing me 1000 Half-Moons -> 10000 Money. It should show 1000 Money -> 100 Half-Moons. It looks weird. We place the maximum we desire to exchange for the minimum we can get.

The Conversion Scale is dividing (`(amount * to_rate) / from_rate`), not multiplying:
For example: `Moinees` has a rate of `x0.5`, `Coins` has a rate of `x1`, and `Pounds` has a rate of `x3`.
 
 - 1 Coin is 2 Moinees ( `(1 * 1) / 0.5` )
 - 1 Pound is 6 Moinees ( `(1 * 3) / 0.5` )
 - 10 Pounds is 30 Coins ( `(10 * 3) / 1`)
 And so on.
 
 If your conversion scale matches up with this formula, you can create another issue as a bug with the display not working correctly.
 
> I could recommend that in the exchange GUI. When someone just does /exchanges. Have 4- 8 buttons the default economy. That starts at 100. And you can add 100-1k-10k to add or remove what is the minimum economy you desire to the maximum you can get.

Buttons in the Exchange GUI are planned for 1.6.2, but thank you for the input.

> Probably sounds difficult but could help to untrained users for easy access.
> 
> @ Also I am not so sure about how to put the default economy I desire into the vault (I know I can type them but not sure if it works or not) I want Money to be the default.

In `functionality.yml`, there is a setting called `VaultEconomy`, you can specify the Economy's name and it will be the only one registered in Vault. If not, all of them are registered in Vault, and the only one used is the one highest alphabetically.

Vault's Convert command calls the equivalent of the `/convert` or `/exchange` command and doesn't actually change the registered economy. If you want to change it, do it so how I specified above.

> I am not completely sure about the implications of registering one economy as default rather than registering them all.

It's just default behavior.

> The problem of default economies keeps going on. I have the belief that is due that all economies are all registered and the one that has alphabetic priority gets to default. Not sure what the implications of registering all economies are.
> 
> But let command facilitate the registration of such default economy my typing the name. If there is implications such as there is no database for the others.
> 
> Show it here. and let do an extra command as /novaecon setdefaultecon confirm I am pretty sure most users would like to be money be by default the most used economy and the other economies as high priority yet individual economies.

Configuration Commands are a good idea! I'll think about implementing them for 1.6.2 or 1.7.0.

> If you got questions about how we can think of a way and you could educate me about the implications. I'll be happy to help regarding critical thinking between users.

Thank you for the suggestions. Please respond to any of the feedback I've shown above.
