### ISSUE TITLE
cannot create economy with CommandVersion 1 in functionality.yml

### ISSUE THREAD

**Issue by Waffl3Development** [Team-Inceptus/Novaconomy#34]
### Bug Type

Compatibility Issues, Console Errors, Other Unexpected Behavior

### Minecraft Version

Paper 1.19.2

### Description

Economy creation fails when CommandVersion in functionality.yml is set to 1. 
[latest.log](https://github.com/Team-Inceptus/Novaconomy/files/9742660/latest.log) (CommandVersion in functionality.yml is set to 1)
There also may be some problems with connecting to the Vault plugin some other plugins that use vault throw errors but will work with other economy plugins like cmi economy or essentials economy.

[log2.log](https://github.com/Team-Inceptus/Novaconomy/files/9742672/log2.log) (CommandVersion in functionality.yml is set to 2)

### Steps to Reproduce

1. install plugin and go set CommandVersion in functionality.yml to 1
2. restart server
3. try to create economy with "novaconomy create {blah} {blah} {blah}" (the spots with the {} are just filler)
4. error message?

### Expected Behavior

economy should be created 

### Actual Behavior

economy is not created and error is thrown

### Additional Info

paper 1.19.2 I also have auto-tune(https://www.spigotmc.org/resources/auto-tune-%E2%9C%85-supply-demand-dynamic-economy-%E2%9C%85-%E2%9A%A11-13-1-19%E2%9A%A1.85715/) installed which throws an error relating something to vault and not finding an economy i think

**Comment by GamerCoder215** [comment]
> ### Bug Type
> 
> Compatibility Issues, Console Errors, Other Unexpected Behavior
> ### Minecraft Version
> 
> Paper 1.19.2
> ### Description
> 
> Economy creation fails when CommandVersion in functionality.yml is set to 1. [latest.log](https://github.com/Team-Inceptus/Novaconomy/files/9742660/latest.log) (CommandVersion in functionality.yml is set to 1) There also may be some problems with connecting to the Vault plugin some other plugins that use vault throw errors but will work with other economy plugins like cmi economy or essentials economy.
> 
> [log2.log](https://github.com/Team-Inceptus/Novaconomy/files/9742672/log2.log) (CommandVersion in functionality.yml is set to 2)
> ### Steps to Reproduce
> 
>     1. install plugin and go set CommandVersion in functionality.yml to 1
> 
>     2. restart server
> 
>     3. try to create economy with "novaconomy create {blah} {blah} {blah}" (the spots with the {} are just filler)
> 
>     4. error message?
> 
> 
> ### Expected Behavior
> 
> economy should be created
> ### Actual Behavior
> 
> economy is not created and error is thrown
> ### Additional Info
> 
> paper 1.19.2 I also have auto-tune(https://www.spigotmc.org/resources/auto-tune-%E2%9C%85-supply-demand-dynamic-economy-%E2%9C%85-%E2%9A%A11-13-1-19%E2%9A%A1.85715/) installed which throws an error relating something to vault and not finding an economy i think

Log indicates that there is no check for a scale argument. Will fix for 1.6.2.
