### ISSUE TITLE
balance placeholder

### ISSUE THREAD

**Issue by Ismasan99** [Team-Inceptus/Novaconomy#39]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.19.1

### Description

So I created a balance called "Arcoins", so I tried to use the placeholder %novaconomy_balance[Arcoins]% but it always shows up 0. Althought I've Got 20000.

### Steps to Reproduce

using placeholder 

### Expected Behavior

To show actual player balance

### Actual Behavior

Always shows 0

**Comment by GamerCoder215** [comment]
Can Confirm this happens. Will continue experimenting and find a fix for 1.7.0

**Comment by GamerCoder215** [comment]
I wasn't aware that you couldn't have placeholders with arguments, meaning that the balance and donated placeholders will have to be removed

If you want to integrate the balance count in your plugin, please use the Novaconomy API, otherwise I can't help you
