### ISSUE TITLE
Wiki, Run commands by paying certain economy and Temporal Permissions by paying economy.

### ISSUE THREAD

**Issue by SimpleWayx** [Team-Inceptus/Novaconomy#44]
### Feature Type

General Feature

### Description of Feature

Hello,
Sorry for not replying back when you were dealing with a previous feature.

I come here to announce that I have been working on a Mohoist server (Mods + Paper server). Could I ask you something?
**First:** Could we work on a Wiki page? 

I have been trying to figure out how to work to limit exchanges thanks to permissions or straight of removing them with permission limitations but I cannot work with little to no reference.
How to control money per entity killed is also unclear to me. Working on the Wiki for better reference seems problematic but it would bring more sense of what the plugin does. To an untrained audience. 

I was excited to see the STONKS feature. But I don't see the features please clarify these steps.

**Second:** I figure out that the GUI balances are arranged in Alphabetic order. Perhaps we could work in a command to arrange the GUI.
For example: Let the user click to place the economy and be placed at the top, So the person doesn't have a complicated GUI organizer. Rather than just a push to the top and the user has to organize in a linear manner. If having to place every currency.

**Third** Can we run a command sharing a particular currency and also ensuring that the user has the required economy? If they do not have that particular currency or the money do not let the command won't run.

Allow running commands by paying a certain currency for a certain time.
That would be great!
I'll be doing touch-ups on my server. Took a long time to figure out certain things from my end.

**Comment by GamerCoder215** [comment]
> ### Feature Type
> 
> General Feature
> ### Description of Feature
> 
> Hello, Sorry for not replying back when you were dealing with a previous feature.
> 
> I come here to announce that I have been working on a Mohoist server (Mods + Paper server). Could I ask you something? **First:** Could we work on a Wiki page?
A wiki page is available [here (https://github.com/Team-Inceptus/Novaconomy/wiki)](https://github.com/Team-Inceptus/Novaconomy/wiki). It currently only has addon information (PlaceholderAPI, Treasury, Vault), but I plan to expand on it when I have the time.

> I have been trying to figure out how to work to limit exchanges thanks to permissions or straight of removing them with permission limitations but I cannot work with little to no reference. How to control money per entity killed is also unclear to me. Working on the Wiki for better reference seems problematic but it would bring more sense of what the plugin does. To an untrained audience.

Considering you're a long-time fan of Novaconomy (thank you), you're configuration may not have been updated to show comments on how to do things.

A Defualt Configuration, available with comments and examples, is available [in this file over here](https://github.com/Team-Inceptus/Novaconomy/blob/master/plugin/src/main/resources/config.yml).

Around 1.3 to 1.5, I added modifiers to killing, mining, farming, fishing, and deaths, based on entity/block types, as well as the ability to add multiple currencies. Examples are available in the file I mentioned above.

> I was excited to see the STONKS feature. But I don't see the features please clarify these steps.
> 
> **Second:** I figure out that the GUI balances are arranged in Alphabetic order. Perhaps we could work in a command to arrange the GUI. For example: Let the user click to place the economy and be placed at the top, So the person doesn't have a complicated GUI organizer. Rather than just a push to the top and the user has to organize in a linear manner. If having to place every currency.

I hear you're wanting a wheel of different sorting types (A-Z, Z-A, symbol, date added, etc.) That might be a good feature for 1.7.

> **Third** Can we run a command sharing a particular currency and also ensuring that the user has the required economy? If they do not have that particular currency or the money do not let the command won't run.
Not entirely sure what you mean by this. I think you mean that you want commands to be only run if they have a specific balance for an economy.
> Allow running commands by paying a certain currency for a certain time. That would be great! I'll be doing touch-ups on my server. Took a long time to figure out certain things from my end.
Unless you can provide what plugin this is for, It is impossible (or extremely difficult + not supported) to interfere with an external plugin's command logic, without an already supported integration.

If you want to make (or learn how to) a plugin that has this logic, you can integrate it with the Novaconomy API and intercept when a player runs a command. I'd recommend looking on YouTube or other tutorials for how to do this.


These seem like good suggestions! Thanks for the input. I plan to update the Wiki at some point when I have more time, but if you'd like to contribute to the wiki, you can do that too.

**Comment by SimpleWayx** [comment]
> These seem like good suggestions! Thanks for the input. I plan to update the Wiki at some point when I have more time, but if you'd like to contribute to the wiki, you can do that too.

Thanks for your early reply. Sure thing I would like to have permission in order to work on the wiki or have it a format.

> Unless you can provide what plugin this is for, It is impossible (or extremely difficult + not supported) to interfere with an external plugin's command logic, without an already supported integration.

I was hoping for essentials, RTP and /Back command.

I have a coin called "Checkpoints" which I don't want it to be brought by any exchange.

I was thinking when they do /home, /RTP and /back they should have a cost in order to limit such features.

Making a Server Shop that sells the currency. Obviously is just to limit the progression in server mods that are mostly RPG / Roleplay.

Thanks for your advise.

**Comment by GamerCoder215** [comment]
This update will also include 1.19.3 support.

**Comment by GamerCoder215** [comment]
Scratch that: 1.19.3 Support is now readily available.
https://www.spigotmc.org/resources/novaconomy.100503/update?update=482415

**Comment by GamerCoder215** [comment]
Hello,

ETA for v1.7 is February 5th. This may change by up to 2 weeks.

Essentials **does** have API to modify the functionality of those commands, so I'll also include support for those in v1.7.
Thanks for your patience :)

**Comment by SimpleWayx** [comment]
LETS GO!

You should Publish your Plugin in Modorith as a full-fledged  economy
Plugin.

**Comment by GamerCoder215** [comment]
v1.7.0 will release shortly. Markets had to be delayed because of time constraints.

Marking as closed.
