### ISSUE TITLE
Help with commands & a Question for a feature

### ISSUE THREAD

**Issue by Nesokk** [Team-Inceptus/Novaconomy#51]
### Feature Type

General Feature

### Description of Feature

Dear dev,

i just installed your Plugin on my minecraft server, but i have proplems to set it up.

1.  Most of the time there comes a error, or there stand no-subcommand-specified

2. I think that the plugin is hard to set up and wanted to ask you if you are able to create a guide

thx for creating such a amazing plugin and for reacting, have a nice day.

**Comment by GamerCoder215** [comment]
Hello,

A wiki page for plugin setup and usage is under development (see #44).

I'm currently distracted with other projects at the moment, so there is no official ETA, but a guide and/or wiki will be available in the near future.

**Comment by Nesokk** [comment]
hello,

I really REALLY enjoy your plugin with my friends, but we need the feature, that you can like drop 3 diamonds and then get a 
custom price. For better understanding, we have a villager shop and there you can change diamonds for things or buy things with diamonds. And there we want to transfer diamonds into money. And i constructed a inflation system and for that it were nice, if there is a line in the config where we can define the value for the diamond. 

I hope you understand it even when i arent that good in english and explaining, also i dont know how hard it is to code something like that, but i guess it would be very nice and also a nice secment in your Plugin 

Have a nice day
I

**Comment by GamerCoder215** [comment]
Hello,

Stock Markets (the feature you are describing) is a planned out feature for 1.7.0. I have laid out the configuration methods, inflation rates, GUIs, and other concepts already, but again, there is no ETA for a release yet.

Thank you for your patience.

**Comment by GamerCoder215** [comment]
Hello,

An emerging wiki page is available on the "Wiki" tab. Currently, all important  commands and command-related documentation have been finished.

Marking as closed.
