### ISSUE TITLE
Making a business product breaks the plugin.

### ISSUE THREAD

**Issue by Pigioo** [Team-Inceptus/Novaconomy#60]
### Bug Type

Console Errors

### Minecraft Version

1.19.3 and 1.18.2

### Description

Whenever i create a product on my business it says "made a new product for Air" makes the plugin unresponsive, restarting dosent fix it. Also whenever i first use the plugin it dosent work and i have to restart again for it to work. 

### Steps to Reproduce

Make a business
Make a new product

### Expected Behavior

It should make a product and the plugin should not break once making a product.

### Actual Behavior

It automatically makes the product as air, and breaks the plugin.

**Comment by GamerCoder215** [comment]
Hello,
Are you holding the item you want to sell? Or are you simply running the command?

I may have never added an error message that directs you to this action.

**Comment by Pigioo** [comment]
I have it in my hand, and 
![image](https://user-images.githubusercontent.com/126029179/220718923-0c114bfc-f4ca-427a-a886-67f13555d567.png)
this is what happens
![image](https://user-images.githubusercontent.com/126029179/220718994-c9335393-a94a-4ed9-9e8c-7334a5856caf.png)

**Comment by Pigioo** [comment]
Starting the server also gives out an error. 
![image](https://user-images.githubusercontent.com/126029179/220725745-f352f5f6-d057-45c9-98db-7fb0de886f7a.png)

**Comment by GamerCoder215** [comment]
Fixed in 0b888ee. Will update to SpigotMC soon.
