### ISSUE TITLE
Custom model data currency and icon

### ISSUE THREAD

**Issue by Ismasan99** [Team-Inceptus/Novaconomy#8]
### Feature Type

Compatibility

### Description of Feature

Is it possible to haven a custom item as a coin and also a custom tag created with oraxen for currency icon?

**Comment by GamerCoder215** [comment]
> ### Feature Type
> 
> Compatibility
> ### Description of Feature
> 
> Is it possible to haven a custom item as a coin and also a custom tag created with oraxen for currency icon?

Yes! It would be possible; The easiest way to implement this would be to create a model data command that sets the integer ID for it; would this work for you?

**Comment by Ismasan99** [comment]
yes perfect, thanks!!

**Comment by GamerCoder215** [comment]
Marking as closed, added in v1.5.1.
