### ISSUE TITLE
Set Amount is broken

### ISSUE THREAD

**Issue by TapTapOLY** [Team-Inceptus/Novaconomy#89]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.20

### Description

Clicking set amount on market open does not work. It auto closes it before you can type

### Steps to Reproduce

/market open
Select something to buy
Click Set Amount
It closes

### Expected Behavior

To allow me to set amount

### Actual Behavior

It closes the menu down

**Comment by GamerCoder215** [comment]
1.20 updated the way sign prompts happen. I'll work on a fix shortly.

**Comment by GamerCoder215** [comment]
Fixed in c5480d0. Please redownload the plugin from GitHub or any other plugin provider.
