### ISSUE TITLE
Taxes Revamped

### ISSUE THREAD

**Issue by PaxJaromeMalues** [Team-Inceptus/Novaconomy#94]
### Feature Type

General Feature

### Description of Feature

I hope I understand the way this works with Vault. Excuse me if I haven't grasped the functionality yet, I am pretty new.
If it is possible I would like to request the following features:

A) Taxes per each players registered income (think: `valueA=last account balance` `valueB=current account balance at tax event` `valueC=valueA - valueB | the amount of 'income' to be taxed, if negative (player 'lost' money) no taxes are applied`) as an option to the current taxes on the entire account balance.

B) Taxes can be transfered to an account like in Request C

C.) An Account per economy that can be used as the 'government' treasury only players with a specific perm have access to.
I would use it like this:
1. Players sell and buy items and their accounts change accordingly.
2. Players are taxed as per Request A
3. On special Events 'government' can use the tax income to provide tools, food and materials when public infrastructure needs to be build or stuff along this line. These would be bought from the players shops with whatever amount of taxes were collected.
So the activity of players and there selling buying from eachothers shops kinda also digtates what the government can afford to build.

Thank you for providing Novaconomy plugin to the community 👍

**Comment by GamerCoder215** [comment]
An interesting idea for v1.8.0.

>     2. Players are taxed as per Request A
Would this income be classified as via Business income? Or are you thinking of something else?

>     3. On special Events 'government' can use the tax income to provide tools, food and materials when public infrastructure needs to be build or stuff along this line. These would be bought from the players shops with whatever amount of taxes were collected.
>        So the activity of players and there selling buying from eachothers shops kinda also digtates what the government can afford to build.

This 'government balance' would most likely go to the already implemented Banks feature for a better experience so players can withdraw and use their money accordingly. I may also implement a feature where Banks offer other things to give out, such as item resources or others.

**Comment by PaxJaromeMalues** [comment]
Example A is a bit simplistic in its way of calculating `valueC` but I guess it is easier compared to actually running a db over all server transactions and then calculate the real income per account to be taxed.

**Comment by PaxJaromeMalues** [comment]
I think a good inspiration can be the spigot plugin 'quicktax' it does not exactley achieve the same as requested, but could serve as an example.

> Would this income be classified as via Business income? Or are you thinking of something else?

I am currently taxing each individual player account. Once (more like if) people start forming buisnesses I would like to apply higher taxes to the buisness income, as they generate a lot more money. I am unsure tho about if I will use buisnesses/companies at all, as I am not too familiar with these features of Novaconomy and how well they play together with simple sign-shops placed by players, which is currently the main form of trade.

If Nova would be able to hook with the plugin 'CourierNew' for deliveries of goods bought on the Novaconomy-market (the GUI market) applying a fee for long delayed or short delayed delivery to the buyer, that would be another thing, that could further the exceptance of buisness and corporate level economy.

**Comment by GamerCoder215** [comment]
> I think a good inspiration can be the spigot plugin 'quicktax' it does not exactley achieve the same as requested, but could serve as an example.
I'll take a look at the plugin, thank you for the suggestion.
 
> > Would this income be classified as via Business income? Or are you thinking of something else?
>
> I am currently taxing each individual player account. Once (more like if) people start forming buisnesses I would like to apply higher taxes to the buisness income, as they generate a lot more money. I am unsure tho about if I will use buisnesses/companies at all, as I am not too familiar with these features of Novaconomy and how well they play together with simple sign-shops placed by players, which is currently the main form of trade.

What I might do is to keep the old tax system but also add new features such as taxable business, paying, market selling, and other ways players get money for the purpose of these features while also ensuring backward compatibility.
 
> If Nova would be able to hook with the plugin 'CourierNew' for deliveries of goods bought on the Novaconomy-market (the GUI market) applying a fee for long delayed or short delayed delivery to the buyer, that would be another thing, that could further the exceptance of buisness and corporate level economy.

Since CourierNew is no longer maintained I can't guarantee a hook since it doesn't support 1.20, but I may keep it in mind.

**Comment by PaxJaromeMalues** [comment]
> > I think a good inspiration can be the spigot plugin 'quicktax' it does not exactley achieve the same as requested, but could serve as an example.
> 
> I'll take a look at the plugin, thank you for the suggestion.
> 
Do not stress yourself m8.
> > > Would this income be classified as via Business income? Or are you thinking of something else?
> > 
> > 
> > I am currently taxing each individual player account. Once (more like if) people start forming buisnesses I would like to apply higher taxes to the buisness income, as they generate a lot more money. I am unsure tho about if I will use buisnesses/companies at all, as I am not too familiar with these features of Novaconomy and how well they play together with simple sign-shops placed by players, which is currently the main form of trade.
> 
> What I might do is to keep the old tax system but also add new features such as taxable business, paying, market selling, and other ways players get money for the purpose of these features while also ensuring backward compatibility.
> 
That sounds like a perfectly reasonable decision.
> > If Nova would be able to hook with the plugin 'CourierNew' for deliveries of goods bought on the Novaconomy-market (the GUI market) applying a fee for long delayed or short delayed delivery to the buyer, that would be another thing, that could further the exceptance of buisness and corporate level economy.
> 
> Since CourierNew is no longer maintained I can't guarantee a hook since it doesn't support 1.20, but I may keep it in mind.
I just saw that the last commit is 1year ago but the authors last comment on spigotmc was in febuary but sofar nothing has changed in the guthub project. I might need to look for a new postal service plugin, damn it. Thanks for making me aware of this, I will switch this out before I release my server to the public, just to be safe. Just need to find an alternativ in the spigot jungle, yikes ...

**Comment by GamerCoder215** [comment]
> A) Taxes per each players registered income (think: `valueA=last account balance` `valueB=current account balance at tax event` `valueC=valueA - valueB | the amount of 'income' to be taxed, if negative (player 'lost' money) no taxes are applied`) as an option to the current taxes on the entire account balance.

This has been implemented with the 1997edf commit.

> B) Taxes can be transfered to an account like in Request C

> C.) An Account per economy that can be used as the 'government' treasury only players with a specific perm have access to. I would use it like this:
> 
>     1. Players sell and buy items and their accounts change accordingly.
> 
>     2. Players are taxed as per Request A
> 
>     3. On special Events 'government' can use the tax income to provide tools, food and materials when public infrastructure needs to be build or stuff along this line. These would be bought from the players shops with whatever amount of taxes were collected.
>        So the activity of players and there selling buying from eachothers shops kinda also digtates what the government can afford to build.

Both of these features have *relatively* been implemented already: Banks get income from various sources, and an added source is the income tax feature you have specified. Players can withdraw from the banks for their own purposes (i.e. buying materials from businesses/novaconomy market). If you have any more thoughts please let me know.
