### ISSUE TITLE
novaconomy command aliases

### ISSUE THREAD

**Issue by PaxJaromeMalues** [Team-Inceptus/Novaconomy#95]
### Feature Type

Compatibility

### Description of Feature

I'd highly recommend, that the following command aliases do not forward to novaconomy to avoid server administrator confusion with other administrative plugins like papers timing stats, control plugins for teleport spawn and mysql rates, bounty plugins and plugins for performance messurements.
Considering large servers usually use way above 100 plugins this whole command thing can go haywire real quick if too common words are used.
There are reasons why most of these common-word commands have not been implemented by other developers.
Alternatively these aliases could be configed as opt-in.

```console
/settings - Manage your Novaconomy Settings | novaconomy.user.settings
/bounty - Manage your Novaconomy Bounties | novaconomy.user.bounty
/convert - Convert one balance in an economy to another balance | novaconomy.user.convert
/rate - Rate a Novaconomy Business | novaconomy.user.rate
/statistics - View your Novaconomy Statistics | novaconomy.user.stats
```

**Comment by GamerCoder215** [comment]
I may remove some of the aliases and append `nova` or `n` as well for v1.8.0. And if I can ask, what plugins are these commands conflicting with?

**Comment by PaxJaromeMalues** [comment]
> I may remove some of the aliases and append `nova` or `n` as well for v1.8.0. And if I can ask, what plugins are these commands conflicting with?

Oh, I am sorry, I did not want to imply direct conflicts but rather wanted to point towards the issue administrators might confuse these commands with other plugins as their wording is rather unspecific like "settings".
