### ISSUE TITLE
Help with bedrock users

### ISSUE THREAD

**Issue by zvecy** [Team-Inceptus/Novaconomy#98]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.19

### Description

Hey my bedrock player says, his money doesnt work, its like novaeconomy that doesnt work him on scoreboard it displays %vault% instead of money for him and in some sellgui pugins he doesnt get money when selling items, i ccannot contact plugin developer cuz they dont have a discord

### Steps to Reproduce

Hey my bedrock player says, his money doesnt work, its like novaeconomy that doesnt work him on scoreboard it displays %vault% instead of money for him and in some sellgui pugins he doesnt get money when selling items, i ccannot contact plugin developer cuz they dont have a discord

### Expected Behavior

I dont know to work?

### Actual Behavior

There isnt any i suppose

### Additional Info

Hey my bedrock player says, his money doesnt work, its like novaeconomy that doesnt work him on scoreboard it displays %vault% instead of money for him and in some sellgui pugins he doesnt get money when selling items, i ccannot contact plugin developer cuz they dont have a discord

**Comment by GamerCoder215** [comment]
> Hey my bedrock player says, his money doesnt work, its like novaeconomy that doesnt work him on scoreboard it displays %vault% instead of money for him and in some sellgui pugins he doesnt get money when selling items, i ccannot contact plugin developer cuz they dont have a discord

1. This plugin isn't a MC Bedrock plugin addon; Are you using GeyserMC?
2. I do not plan to ensure MC Bedrock support, espeically if it is an issue with Vault or GeyserMC

If you can clarify what you'll mean I'll reopen this issue.
